# Generated by Django 5.2.8 on 2025-12-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='img',
            field=models.URLField(default=''),
        ),
    ]
